name: sample-react
domains:
- domain: mleach.dev
  type: PRIMARY 
  zone: mleach.dev
services:
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: Submohr/mjleach-dev-sample
  name: sample-react
